---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | sh
    creates=/home/{{ username }}/.nvm/nvm.sh
  become_user: "{{ username }}"

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ item }}"
  register: output
  become_user: "{{ username }}"
  changed_when: "'already installed.' not in output.stderr"
  with_items:
    - "{{ nvm_node_versions }}"

- name: Install default packages
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm use {{ item.0 }} && npm install -g {{ item.1}}"
  become_user: "{{ username }}"
  with_nested:
    - "{{ nvm_node_versions }}"
    - "{{ nvm_packages }}"

- name: Set node default
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm alias default {{ nvm_default_node_version }}"
