---
# Ubuntu/Debian users might want to install the dkms package to ensure that the VirtualBox host kernel modules (vboxdrv, vboxnetflt and vboxnetadp) are properly updated if the linux kernel version changes during the next apt-get upgrade
- name: Ubuntu/Debian kernel module fix
  apt:  pkg={{item}} state=latest
  become: true
  with_items:
      - dkms

- name: virtualization | Download Virtualbox
  get_url: url={{ virtualbox_url }} dest={{ virtualbox_deb_package }}
  
- name: virtualization | Fix any broken depedencies
  become: yes
  command: apt-get -f -y install
  
# if it fails see http://askubuntu.com/questions/456183/what-does-unknown-media-type-in-type-all-all-mean
# Unknown media type in type 'all/all' 
- name: virtualization | Install Virtualbox
  become: yes
  command: dpkg --skip-same-version -i {{ virtualbox_deb_package }}
  
- name: virtualization | Download Vagrant
  get_url: url={{ vagrant_url }} dest={{ vagrant_deb_package }}
  
- name: virtualization | Install Vagrant
  become: yes
  command: dpkg --skip-same-version -i {{ vagrant_deb_package }}
