---
- name: update the apt cache
  apt: update_cache=yes
  become: true

- name: ensure packages are installed (python support)
  apt:  pkg={{item}} state=latest
  become: true
  with_items:
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libpq-dev
      - python
      - python-dev
      - python-virtualenv
      - python-pip
  
- name: ensure packages are installed (image support)
  apt:  pkg={{item}} state=latest
  become: true
  with_items:
      - libtiff5-dev
      - libjpeg8-dev
      - zlib1g-dev
      - libfreetype6-dev
      - liblcms2-dev
      - libwebp-dev
      - tcl8.6-dev
      - tk8.6-dev
      - python-tk

- name: ensure packages are installed (ldap support)
  apt:  pkg={{item}} state=latest
  become: true
  with_items:
      - libsasl2-dev
      - libldap2-dev
      - libssl-dev

- name: ensure various packages are installed
  apt:  pkg={{item}} state=latest
  become: true
  with_items:
      - git
      - vim
      - makepasswd
      - gimp
      - xsane
